name = "p-ode.com"
type = "javascript"
workers_dev = false
route = "p-ode.com/*"
account_id = "96f2fde5b6ccfc46920c02e2f787181e"
zone_id = "d4bf5bf47751326b0cb733b4b2431531"

kv-namespaces = [
    { binding = "wranglerKV", id = "06779da6940b431db6e566b4846d64db" }
]

[vars]
variable1 = "somevalue"

[secrets]
mysecret = "not4u"

[secrets.foo]
bar = 'shhh'
